data:
  raw_data_dir: ../knee_us_segmentation/data/nnUNet_raw
  results_dir: models
  train_dataset: Dataset071_Sonix-Touch
  test_datasets:
    - Dataset070_Clarius_L15
    - Dataset071_Sonix-Touch
    - Dataset072_GE_LQP9
    - Dataset073_GE_LE
  test_split: all
  fold: 0

model:
  name: dinov3
  probe: upernet
  variant: convnextt
  injector: false
  train_encoder: true
  run_name: convnextt_upernet_ft_ours
  checkpoint: null

training:
  epochs: 100
  min_epochs: 20
  early_stopping_patience: 12
  early_stopping_min_delta: 0.001
  batch_size: 2
  encoder_batch_size: 4
  num_workers: 4
  learning_rate: 0.001
  encoder_learning_rate: 0.00001
  encoder_layer_decay: 0.9
  weight_decay: 0.01
  seed: 0
  device: cuda
