data:
  raw_data_dir: ../monounetv2/data/nnUNet_raw
  results_dir: models
  train_dataset: Dataset084_KidneyUS_Philips
  test_datasets:
    - Dataset084_KidneyUS_Philips
    - Dataset085_KidneyUS_Other_Devices
  test_split: Tr
  fold: 0

model:
  name: sam3
  probe: linear
  run_name: linear_finetune_wd1.0
  train_encoder: true
  init_from: linear
  checkpoint: null

training:
  epochs: 20
  min_epochs: 5
  early_stopping_patience: 5
  early_stopping_min_delta: 0.001
  batch_size: 1
  encoder_batch_size: 1
  num_workers: 4
  learning_rate: 0.0001
  weight_decay: 1.0
  seed: 0
  device: cuda
  encoder_learning_rate: 0.00001
  accumulation_steps: 8
